# mapping aliases to character names
aliases = {
    'chewbacca': 'Chewbacca',
    'wookie': 'Chewbacca',
    'chewy': 'Chewbacca',
    'chewie': 'Chewbacca',
    'r2d2': 'R2-D2',
    'droid': 'R2-D2',
    'r2': 'R2-D2',
    'r2-d2': 'R2-D2',
    'r2-d2': 'R2-D2',
    'yoda': 'Yoda',
    'master-yoda': 'Yoda',
    'leia': 'Princess Leia',
    'princess': 'Princess Leia',
    'princess leia': 'Princess Leia',
    'luke': 'Luke Skywalker',
    'skywalker': 'Luke Skywalker',
    'luke skywalker': 'Luke Skywalker',
    'han': 'Han Solo',
    'solo': 'Han Solo',
    'han solo': 'Han Solo',
    'c3p0': 'C-3PO',
    'c-3p0': 'C-3PO',
    'c3po': 'C-3PO',
    'c-3po': 'C-3PO',
    'obi-wan': 'Obi-Wan Kenobi',
    'kenobi': 'Obi-Wan Kenobi',
    'ben': 'Obi-Wan Kenobi',
    'obi': 'Obi-Wan Kenobi',
    'obi-wan kenobi': 'Obi-Wan Kenobi',
    'emperor': 'Emperor Palpatine',
    'palpatine': 'Emperor Palpatine',
    'sidious': 'Emperor Palpatine',
    'emperor palpatine': 'Emperor Palpatine',
    'vader': 'Darth Vader',
    'darth': 'Darth Vader',
    'darth vader': 'Darth Vader',
    'storm': 'Storm Trooper',
    'trooper': 'Storm Trooper',
    'stormtrooper': 'Storm Trooper',
    'storm trooper': 'Storm Trooper',
    'boba': 'Boba Fett',
    'fett': 'Boba Fett',
    'boba fett': 'Boba Fett'
}
